### ISSUE TITLE
Add to [m_requirectcp] to show the CTCP response to #chanlog

### ISSUE THREAD

**Issue by EpicNet** [inspircd/inspircd-contrib#198]
Add to the module “_m_requirectcp.cpp_” if the requested CTCP response from the connected client is received so that it can be seen in the log channel when SnoMask (**+p**) is enabled, with the option to add your own response prefixes. And if there was no answer, then add the ability to set a ban for a specific time.

**Prefix identifiers:** $nick, $ident, $ip, $host, $version

**Setup example:**
`<requirectcp ctcp="VERSION" accepted="Check passed" chanlog="yes" prefix="VERSION: $nick \"$version\"" declined="Your client does not respond to CTCP requests" gline="yes" period="1h">`

**Log response example:**
> [12:45:18] <myserver: VERSION: User "_my client v.1.0.0 by Master_"

**Comment by NikosPapakonstantinou** [comment]
The last version supports snomask
`ServerInstance->SNO->EnableSnomask('p', "REQUIRECTCP");`
and
`ServerInstance->SNO->WriteGlobalSno('p', "Suspicious connection on port %d (class %s) from %s (%s) was blocked by m_requirectcp"`
which monitors the denied connect attempts. These connections are not reaching your server and you shouldn't ban them. If someone spams, m_conn_throttle is the right module.

The module modification request has been completed and you can find the updated version here: [https://github.com/inspircd/inspircd-contrib/blob/master/2.0/m_requirectcp.cpp](https://github.com/inspircd/inspircd-contrib/blob/master/2.0/m_requirectcp.cpp)
