### ISSUE TITLE
Channel OP exemption "slowmode" doesn't work with m_slowmode

### ISSUE THREAD

**Issue by aqst** [inspircd/inspircd-contrib#238]
The channel OP exemption "slowmode" (using m_exemptchanops) doesn't seem to work properly with the m_slowmode module.

After using "/mode +W u3:20" to set slow mode and "/mode +X slowmode:v" to set a channel exemption, users with mode +v and higher still aren't able to write more than 3 messages every 20 seconds.

I'm not familiar with C++ but I compared the current code with the code for version 2.0 and it looks like there might be a return missing after line 171, which is present on line 164 in the 2.0 code.
Perhaps it's because of that or otherwise it could just be something wrong with my configuration

**Comment by genius3000** [comment]
Thanks for the bug report, this is now fixed!
