### ISSUE TITLE
[Suggestion] Extra example conf file for contrib modules.

### ISSUE THREAD

**Issue by gokturkyilmaz** [inspircd/inspircd-contrib#250]
I think that would be more better, as default in inspircd.conf; if there was an extra example conf. file, including contrib modules like <include file="contrib-modules.conf">

Thanks.

**Comment by SadieCat** [comment]
Contrib modules aren't supported so we won't ship configs for them. It would be nice to have example configs on the contrib site when that eventually gets made though.

**Comment by SadieCat** [comment]
As of v4 modulemanager will give you the stuff you need to add your config when you install a module.
