### ISSUE TITLE
m_identifymsg showing multiple line prefixes

### ISSUE THREAD

**Issue by voidzero** [inspircd/inspircd-contrib#251]
Some clients report that they see multiple line prefixes like in the attached screenshot.
I've disabled the module because we're not using it, but I'd still like to report this as a (possible) bug.

![7cf1116af85a9412](https://user-images.githubusercontent.com/1332504/104776671-b3da8000-577a-11eb-870d-c1152bae8574.jpg)

**Comment by voidzero** [comment]
The prefixes also seem to come and go. On my client (weechat 2.5, will upgrade soon lol), I have seen this happen too: sometimes the prefix is there, sometimes it's not.

**Comment by SadieCat** [comment]
What does `grep identifymsg .modulemanager` output?

**Comment by voidzero** [comment]
The output is `3.0.663`.

**Comment by voidzero** [comment]
That's one solution :laughing:
