### ISSUE TITLE
ASN Module  webirc 

### ISSUE THREAD

**Issue by H7-25** [inspircd/inspircd-contrib#253]
whois report webirc gateway asn instead of user's asn

**Comment by SadieCat** [comment]
Does the latest update fix this issue (note: asn info is only fetched for newly connected users).

**Comment by H7-25** [comment]
It look fixed , most of webirc user anyway have not it set because of timeout. I think the problem is the double query for webircgateway (in my case localhost) and for the real user ip. Rising up ircd dns timeout don't help.
