### ISSUE TITLE
non-client tags aren't included in chanhistory

### ISSUE THREAD

**Issue by rgraff** [inspircd/inspircd-contrib#260]
I'm using chanhistory and customtags modules (v3.9.0). When the history is sent, it includes tags like msgid but not the vendor tags. I've added some debug logging to chanhistory and when the HistoryItem is created, the tags_out in MessageDetails does not have the vendor tags.

@SadieCat said "thats a known issue. non-client tags aren't stored due to limitations in how the tag api in v3 works" but that she could fix it "just for the customtags module"

**Comment by SadieCat** [comment]
https://github.com/inspircd/inspircd-contrib/compare/master...SadieCat:customtags-chanhistory is untested but should work, can you test it?

**Comment by SadieCat** [comment]
Ah I missed marking the tag as being processable. The new version in that branch should fix this without any changes to chanhistory.

**Comment by rgraff** [comment]
Testing new commits... In the new OnProcessTag `IS_LOCAL(user)` returns false so the tags don't appear when the history is sent.

**Comment by SadieCat** [comment]
Does it work if you remove the IS_LOCAL check?

**Comment by rgraff** [comment]
Confirmed. If I remove the IS_LOCAL check, it works as expected.
