### ISSUE TITLE
FakeMsg Module

### ISSUE THREAD

**Issue by md-5** [inspircd/inspircd-contrib#68]
Hi,

I'd like to see a module in a similar vein to pretenduser, but rather than mimicking an online user, it simply send the specified privmsg to the channel. If the spoofed user happens to be on the channel, they too will see the message.

I want to make my bridge bot slightly better as pretenduser doesn't allow arbitrary users.

**Comment by Elizafox** [comment]
> Hi,
> 
> I'd like to see a module in a similar vein to pretenduser, but rather than mimicking an online user, it simply send the specified privmsg to the channel. If the spoofed user happens to be on the channel, they too will see the message.
> 
> I want to make my bridge bot slightly better as pretenduser doesn't allow arbitrary users.

m_roleplay may do what you want.

**Comment by SadieCat** [comment]
This has been implemented - https://github.com/inspircd/inspircd-contrib/blob/master/3.0/m_relaymsg.cpp
